version: '3.8'

services:
  # Firebrand itself
  app:
    # Instructing docker to build the Ruby image using the Dockerfile in this project
    build: .
    ports:
    # Maps host PORT 9999 to container PORT 9999
      - "9999:9999"
    environment:
    # Defines environment variable REDIS_URL used in Firebrand
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://rinha:rinha2025@postgres:5432/rinha_db
    depends_on:
    # Ensure that listed services starts before Firebrand
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
    # Connects app service to same network as Redis
      - rinha_network
      - payment-processor
    # Resources definition
    deploy:
      resources:
        limits:
          cpus: "0.5" # Exemplo: 0.5 CPU
          memory: "128MB" # Exemplo: 128MB de RAM para o seu app

  # Redis service
  redis:
    image: redis:7-alpine
    ports:
    # Optional: Maps Redis default Port to host. Useful for CLI access
      - "6379:6379"
    networks:
    # Connects app service to same network as Redis
      - rinha_network

  postgres:
    image: postgres:16-alpine
    environment:
      # Database credentials
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha2025
      POSTGRES_DB: rinha_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - rinha_network
    healthcheck:
      # Command to check service health
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinha_db"]
      # Verification frequency
      interval: 5s
      # Time limit to test command timeout
      timeout: 5s
      # Retry numbers to consider unhealthy
      retries: 5
      # Time in seconds to service start without healthcheck
      start_period: 10s

# Defining a shared network so the services may communicate with themselves
networks:
  rinha_network:
    driver: bridge
  payment-processor:
    external: true
